### ISSUE TITLE
[doc] `diminactive_use_syntax` turns of syntax highlighting in all buffers.

### ISSUE THREAD

**Issue by matthiasbeyer** [blueyed/vim-diminactive#10]
What the title says.

Tell me what information you need to test this.

**Comment by blueyed** [comment]
The idea of the method is to do so.

I've just added some first tests for it (8d0931c).

There is a problem when using `:sp`, or when a buffer is displayed in multiple windows: because it's inactive in one of the windows, `syntax` is turned off (also for the current window).
Is that the issue you are seeing?

Otherwise, a test case to reproduce what you mean would be helpful.

**Comment by matthiasbeyer** [comment]
Whop. Works like a charm. I'm sorry. Maybe you should state this behaviour more clearly!

**Comment by blueyed** [comment]
Ok, the documentation could be improved probably and then there's also the issue with multiple windows using the same buffer.

What do you think how `:sp` should behave? Should syntax be kept enabled for the buffer (which is displayed in two windows then)?
(the problem is that `syntax` is a buffer-local (and not window-local) setting)

**Comment by matthiasbeyer** [comment]
I guess it would be best to keep syntax highlighting enabled for the current _file_. So if it is opened in 2 or more buffers, that's the users fault. But that's just IMHO.

**Comment by blueyed** [comment]
Agreed.

**Comment by kelvinst** [comment]
@blueyed any advance in this? :grin:

**Comment by blueyed** [comment]
@kelvinst 
Check out https://github.com/blueyed/vim-diminactive/pull/21 for the fix.

It is missing documentation and a test, but seems to work in my quick test (I am not using this method myself).

**Comment by kelvinst** [comment]
@blueyed perfect! works exactly as mentioned above :)
